### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [dk-liang/CLTR#1]
Hi, tks for the interesting work.

Can you upload model to google drive or onedrive?

I can't download model from baidu.

**Comment by dk-liang** [comment]
sorry, I do not have enough space on google drive and onedrive. I will try to solve it.

**Comment by dk-liang** [comment]
> Hi, tks for the interesting work.
> 
> Can you upload model to google drive or onedrive?
> 
> I can't download model from baidu.

please download from https://drive.google.com/file/d/1bccQIMeYBrEsgLAbWgxFE2sOsEhE2EKC/view

**Comment by NguyenVanThanhHust** [comment]
Tks you.
