### ISSUE TITLE
Training with NWPU

### ISSUE THREAD

**Issue by henvh** [dk-liang/CLTR#11]
Hello,
I wanted to train the model on the NWPU dataset and since I am located in Germany I can't download the resized NWPU dataset from baidu - hence  I took the 'preprocessing' from the JHU dataset and applied it to the original NWPU dataset. I started the training with the parameters given by your provided log-file, but the model didn't learn anything (MAE and MSE were constant). I tried it with a bigger learning rate, but that gave me an error with the cost matrix (matrix contains invalid numeric entries) when calculating the linear sum assignment (matcher.py line 80 for linear_sum_assignment from scipy.optimize).
I wondered if the resized NWPU dataset you provided on baidu has some other characteristics than applying the JHU preprocessing to the original NWPU? What could possibly be another reason for such a behavior?
Thanks.

**Comment by dk-liang** [comment]
I will upload the datasets into Onedrive as soon as possible

**Comment by dk-liang** [comment]
You can download from https://1drv.ms/u/s!Ak_WZsh5Fl0lhF0V7sxTVv1Vs0Aq?e=drd48k

**Comment by henvh** [comment]
Thanks!
