### ISSUE TITLE
why is train_loader and test_loader =0?

### ISSUE THREAD

**Issue by FCgogogo** [dk-liang/CLTR#13]
Not using distributed mode
model params: 43.446471
2023-03-20 08:19:37,507 - CLTR - INFO - model params: = 43.446	
best result: 100000.0
2023-03-20 08:19:37,512 - CLTR - INFO - best result = 100000.000
0
mae 0.0 mse 0.0
0
mae 0.0 mse 0.0
0
mae 0.0 mse 0.0
0
mae 0.0 mse 0.0

**Comment by dk-liang** [comment]
You need to generate the training or test list

**Comment by FCgogogo** [comment]
the NWPU_list have generated three list files

**Comment by dk-liang** [comment]
Maybe you can print the image path to check it
