### ISSUE TITLE
 How can I use the model trained from JHU-CROWD ++ training set to run video_demo.py

### ISSUE THREAD

**Issue by sandydf** [dk-liang/CLTR#16]
Thanks for the interesting work! How can I use the model trained from JHU-CROWD ++ training set to run video_demo.py ? I got size dismatch error.

**Comment by dk-liang** [comment]
Can you share the log?

**Comment by sandydf** [comment]
Traceback (most recent call last):
  File "video_demo.py", line 165, in <module>
    main(params)
  File "video_demo.py", line 47, in main
    model.load_state_dict(new_state_dict)
  File "/home/xxx/anaconda3/envs/CLTR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.query_embed.weight: copying a param with shape torch.Size([500, 256]) from checkpoint, the shape in current model is torch.Size([700, 256]).

**Comment by dk-liang** [comment]
set "--num_queries 500"
