### ISSUE TITLE
Testing help

### ISSUE THREAD

**Issue by congyi-lcy** [dk-liang/CLTR#20]
大佬您好，我按照您的说明文档进行了相应的训练，也达到了同样的训练效果；看到您给出了在nwpu验证集上的测试代码test.py，不过我想在自己的数据集上做个测试看看效果，请问我也需要对我自己的数据集先生成point map吗？（其实这里先生成point map的操作我也有些疑问：论文中说的该方法是区别于之前密度图方法的，那这里要先生成point map的目的是什么呢？）

代码小白，可能问的问题有点低级了...恳请大佬可以帮忙解答一下，如果能提供一下在别的数据集上的测试/推理代码就更好了

**Comment by dk-liang** [comment]
不一定要point map，只是为了方便做可视化分析而已，
所有数据集的流程都是一样的，看懂NWPU和JHU的数据处理就OK了，大概思想就是转化成统一的坐标形式，生成路径文件（npy格式），就可以train了

**Comment by congyi-lcy** [comment]
好的，我自己再去学习学习，感谢大佬认真解答！
