### ISSUE TITLE
mae is same when training

### ISSUE THREAD

**Issue by SherlockHolmes221** [dk-liang/CLTR#25]
mae is same when training my own dataset

**Comment by dk-liang** [comment]
How many GPUs do you use?

**Comment by ly00729** [comment]
I also have the same problem when using the jhu and NWPU datasets. I use one GPU.

**Comment by dk-liang** [comment]
> I also have the same problem when using the jhu and NWPU datasets. I use one GPU.

Try to use my default command

**Comment by ly00729** [comment]
Can you explain it in more detail? I don't quite understand what you said, thank you.

**Comment by dk-liang** [comment]
> Can you explain it in more detail? I don't quite understand what you said, thank you.

Can you try to run with 4 GPUs, I haven't run with 1 GPU.

**Comment by SherlockHolmes221** [comment]
> How many GPUs do you use?

1 GPU and only have one thus can not test on 4

**Comment by SherlockHolmes221** [comment]
> Can you explain it in more detail? I don't quite understand what you said, thank you.

can not predict any person thus the mae not change

**Comment by ly00729** [comment]
> > Can you explain it in more detail? I don't quite understand what you said, thank you.
> 
> Can you try to run with 4 GPUs, I haven't run with 1 GPU.

Okay, I'll give it a try, later. Thank you.

**Comment by pigcat88** [comment]
> > Can you explain it in more detail? I don't quite understand what you said, thank you.
> 
> can not predict any person thus the mae not change

May I ask if the same problem of Mae has been solved?

**Comment by SherlockHolmes221** [comment]
> > > Can you explain it in more detail? I don't quite understand what you said, thank you.
> > 
> > 
> > can not predict any person thus the mae not change
> 
> May I ask if the same problem of Mae has been solved?

No, did not solve

**Comment by dk-liang** [comment]
I haven't tried to train on 1 GPU and may need to adjust some hyperparameters.

**Comment by bartoszptak** [comment]
> I haven't tried to train on 1 GPU and may need to adjust some hyperparameters.

Which parameters? 

**I also cannot reproduce the results using your repository.**

**Comment by bartoszptak** [comment]
I checked the training procedure using 1, 2, and 4 GPUs and all generated the same, unchanging MAE.

**Comment by bartoszptak** [comment]
@SherlockHolmes221 did you solve it? Why did you mark it as completed without any answer?

**Comment by 2226450890** [comment]
Why did you mark it as completed without any answer?  What are you avoiding？？
