### ISSUE TITLE
可视化问题

### ISSUE THREAD

**Issue by UntrainedButLoveCode** [dk-liang/CLTR#32]
我尝试修改video_demo.py得到一个用于图片数据推理结果的可视化代码。但可视化出来的结果并不理想，我用的是自己的数据集，训练了1000轮的最佳模型。一开始我怀疑是可视化代码的问题，因为结果显示的坐标总是出现偏移的现象，跟原图对应不上；后来我直接输入不需要裁剪的大小，同样出现这样的问题，我怀疑CLTR回归出点坐标的方法只是个噱头，预测出来的点坐标，再次经过放缩后，确实在图片大小范围内，但并不准确，也就是说预测出来的点坐标并不可用。其次，点的个数取决于阈值的设置，阈值设置的不好，总数的计算会有很大偏差。虽然论文确实不错，思路也很棒，可惜在我的高密度数据集上不适用。可能点太多，太密集，模型很难训练起来。还是喜欢作者FIDTMap的方法。
![out_image](https://github.com/user-attachments/assets/71de84da-de33-4dc2-a4ad-531e58e7482c)

**Comment by UntrainedButLoveCode** [comment]
读个研，真的伤心，好不容易找到好文章，结果发现搞不起来，真累了啊。

**Comment by dk-liang** [comment]
一般没这个问题。坐标是要归一化的，可能是返归一化的时候，size没对上。

**Comment by UntrainedButLoveCode** [comment]
> 一般没这个问题。坐标是要归一化的，可能是返归一化的时候，size没对上。

可能是我的问题。您可以看我的理解对不对吗？我给模型喂了一张256*256的图片，不进行任何裁剪，模型最后输出的是归一化的坐标，将这个坐标乘上256，理论上就是模型推理的原图上的坐标了吧？
