### ISSUE TITLE
NWPU dataset

### ISSUE THREAD

**Issue by alinadobre** [dk-liang/CLTR#7]
The download link for NWPU dataset does not work. I can not create an account on Baidu as I am located in Germany. Please can you provide the dataset on a different platform?
I tried to download the original one, but I was not able to recreate your results and inference was really bad.

**Comment by dk-liang** [comment]
The resized NWPU dataset we used is about 20 GB. I may need to find a suitable platform to store it, and it needs some time.

**Comment by alinadobre** [comment]
Thank you for your reply, I really appreciate it!
May I suggest if it is easier / possible to make it publicly available on Baidu? 

If I go to the official NWPU dataset, they also have the option to download from Baidu, but over there I don't need to create an account to download it.

**Comment by dk-liang** [comment]
Can you download it from the following link? 
https://pan.baidu.com/s/1GNv3-oCJ5-ksHk1E0RYKuA?pwd=93a8

**Comment by alinadobre** [comment]
![image](https://user-images.githubusercontent.com/71007097/222664521-4d449440-46a8-4d69-86b2-bb8d31dadf44.png)
 The pwd works, but after this it is not possible to download unless I have an account (that I can not create because I have german phone number)

**Comment by dk-liang** [comment]
Okay, I will try to find other platform

**Comment by alinadobre** [comment]
Thank you!! Really appreciate :) 👍

**Comment by dk-liang** [comment]
You can download from https://1drv.ms/u/s!Ak_WZsh5Fl0lhF0V7sxTVv1Vs0Aq?e=drd48k

**Comment by alinadobre** [comment]
Many thanks!!
I wish you all the best! :)
