### ISSUE TITLE
How to calculate the crowd localization metrics?

### ISSUE THREAD

**Issue by windygooo** [dk-liang/CLTR#9]

**Comment by dk-liang** [comment]
Please refer to https://github.com/dk-liang/FIDTM

**Comment by gaoj21** [comment]
From the video_model.pth, it seems that your model trained for more than 2000 epochs, which is different from your experiment settings. Will the number of training epochs affect the final results?

**Comment by dk-liang** [comment]
1500 epoch is enough for NWPU. See the training log https://github.com/dk-liang/CLTR/blob/main/images/NWPU.log

**Comment by Skyninth** [comment]
> Please refer to https://github.com/dk-liang/FIDTM

FIDTM中有计算指标的代码，但是如何得到CLTR的原图尺寸预测坐标呢，请问您可以提供下这个的脚本代码吗，改了好久预测定位结果也还是0.12左右
